platform :ios, '10.0'

target 'MFT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MFT
  
  pod 'Toaster'

end

target 'Widget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Widget
  
  
end
